### ISSUE TITLE
Dividing by 0

### ISSUE THREAD

**Issue by cphyc** [M2-AAIS/BAD#1]
I have the following error:

```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7FA5FAFDDCE8
#1  0x7FA5FAFDCE70
#2  0x7FA5FA4FE67F
#3  0x406A6B in __mod_s_curve_MOD_variables at mod_s_curve.f90:402 (discriminator 4)
#4  0x408AA3 in __mod_s_curve_MOD_curve at mod_s_curve.f90:161 (discriminator 4)
#5  0x408F76 in MAIN__ at main.f90:49
[1]    14158 floating point exception (core dumped)  ./simul
```

it is due to a null-valued sigma_c_thin (see line 161). Maybe we could get rid of the second critical points to solve the problem?

**Comment by ArchangeGabriel** [comment]
Fixed by correctly choosing dichotomy range.
